android:
  allowed_versions:
    - DEVELOPMENT
  url: http://www.google.com
ios:
  allowed_versions:
    - DEVELOPMENT
    - "1.2"
    - "1.3"
  url: http://www.google.com
ios_Production:
  allowed_versions:
    - 1.1-76-g7978a2a
  url: https://testflightapp.com/install/d7ea015ef25a26f507c459e61b98840d-MzMxMjE3Mw/
ios_Staging:
  allowed_versions:
    - 1.1-76-g7978a2a
  url: https://testflightapp.com/install/344bcefb70d03c518ef04770187af23a-MzMxMzQxOQ/
