class AddInitialTagsToDb < ActiveRecord::Migration
  def change
    Tag.create(:name => 'American (Traditional)', :standard => true) 
    Tag.create(:name => 'Bistro', :standard => true) 
    Tag.create(:name => 'Breakfast & Brunch', :standard => true) 
    Tag.create(:name => 'Burgers', :standard => true) 
    Tag.create(:name => 'Cafe', :standard => true) 
    Tag.create(:name => 'Chinese', :standard => true) 
    Tag.create(:name => 'Deli', :standard => true) 
    Tag.create(:name => 'Diner', :standard => true) 
    Tag.create(:name => 'Fast Food', :standard => true) 
    Tag.create(:name => 'Gastropub', :standard => true) 
    Tag.create(:name => 'Gluten-Free', :standard => true) 
    Tag.create(:name => 'Indian', :standard => true) 
    Tag.create(:name => 'Italian', :standard => true) 
    Tag.create(:name => 'Mexican', :standard => true) 
    Tag.create(:name => 'Pizza', :standard => true) 
    Tag.create(:name => 'Sandwiches', :standard => true) 
    Tag.create(:name => 'Soup', :standard => true) 
    Tag.create(:name => 'Steakhouse', :standard => true) 
    Tag.create(:name => 'Sushi Bar', :standard => true) 
    Tag.create(:name => 'Thai', :standard => true) 
    Tag.create(:name => 'Vegan', :standard => true) 
    Tag.create(:name => 'Vegetarian', :standard => true) 
    
    Tag.create(:name => 'Afghan')
		Tag.create(:name => 'African')
		Tag.create(:name => 'Argentine')
		Tag.create(:name => 'Asian Fusion')
		Tag.create(:name => 'Barbeque')
		Tag.create(:name => 'Basque')
		Tag.create(:name => 'Belgian')
		Tag.create(:name => 'Brasserie')
		Tag.create(:name => 'Brazilian')
		Tag.create(:name => 'British')
		Tag.create(:name => 'Buffets')
		Tag.create(:name => 'Burmese')
		Tag.create(:name => 'Cajun/Creole')
		Tag.create(:name => 'Cambodian')
		Tag.create(:name => 'Caribbean')
		Tag.create(:name => 'Creperie')
		Tag.create(:name => 'Cuban')
		Tag.create(:name => 'Ethiopian')
		Tag.create(:name => 'Filipino')
		Tag.create(:name => 'Fish & Chips')
		Tag.create(:name => 'Fondue')
		Tag.create(:name => 'Food Stand')
		Tag.create(:name => 'French')
		Tag.create(:name => 'German')
		Tag.create(:name => 'Greek')
		Tag.create(:name => 'Halal')
		Tag.create(:name => 'Hawaiian')
		Tag.create(:name => 'Himalayan/Nepalese')
		Tag.create(:name => 'Hot Dogs')
		Tag.create(:name => 'Hungarian')
		Tag.create(:name => 'Indonesian')
		Tag.create(:name => 'Irish')
		Tag.create(:name => 'Japanese')
		Tag.create(:name => 'Korean')
		Tag.create(:name => 'Kosher')
		Tag.create(:name => 'Latin American')
		Tag.create(:name => 'Live/Raw Food')
		Tag.create(:name => 'Malaysian')
		Tag.create(:name => 'Mediterranean')
		Tag.create(:name => 'Middle Eastern')
		Tag.create(:name => 'Modern European')
		Tag.create(:name => 'Moroccan')
		Tag.create(:name => 'Pakistani')
		Tag.create(:name => 'Persian/Iranian')
		Tag.create(:name => 'Peruvian')
		Tag.create(:name => 'Polish')
		Tag.create(:name => 'Portuguese')
		Tag.create(:name => 'Russian')
		Tag.create(:name => 'Scandinavian')
		Tag.create(:name => 'Seafood')
		Tag.create(:name => 'Singaporean')
		Tag.create(:name => 'Soul Food')
		Tag.create(:name => 'Spanish')
		Tag.create(:name => 'Taiwanese')
		Tag.create(:name => 'Tapas Bar')
		Tag.create(:name => 'Tapas/Small Plates')
		Tag.create(:name => 'Tex-Mex')
		Tag.create(:name => 'Turkish')
		Tag.create(:name => 'Vietnamese')
    
  end
end
